server:
  port: 8888
  
spring:
  profiles:
    active: native
 
  cloud:
    config:
      server:
        native: # utilizando file-system
          search-locations: C:/microservice-repo
             
  
